version: '3'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: ldap_server
    environment:
      LDAP_ORGANISATION: $LDAP_ORGANISATION
      LDAP_DOMAIN: $LDAP_DOMAIN
      LDAP_ADMIN_PASSWORD: $LDAP_ADMIN_PASSWORD
    ports:
      - $LDAP1_PORT
      - $LDAP2_PORT
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./ldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: ldap_web
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
    ports:
      - $PHP_LDAP_ADMIN_PORT
    depends_on:
      - openldap

  password_notifier:
    build: .
    container_name: password_notifier
    environment:
      SMTP_SERVER: $SMTP_SERVER
      SMTP_PORT: $SMTP_PORT
      SMTP_USER: $SMTP_USER
      SMTP_PASS: $SMTP_PASS
      LDAP_SERVER: ldap_server
      LDAP_USER: $LDAP_USER
      LDAP_PASSWORD: $LDAP_ADMIN_PASSWORD
      BASE_DN: $BASE_DN
      LDAP_FILTER: $LDAP_FILTER
      PASSWORD_EXPIRY_ATTR: $PASSWORD_EXPIRY_ATTR
      LAST_NOTIFY_ATTR: $LAST_NOTIFY_ATTR
      EXPIRY_DAYS: $EXPIRY_DAYS
    depends_on:
      - openldap
    command: sh -c "while true; do python /app/main.py; sleep 60; done"
    volumes:
      - ./logs:/app/logs